# Generated by Django 5.1.2 on 2025-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupportticket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customersupportticket',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
