# Generated by Django 5.1.2 on 2025-04-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_category_product_subcategory'),
        ('ecommerce', '0004_seed_categories'),
    ]

    operations = [
    ]
