# Generated by Django 5.1.2 on 2025-04-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_merge_20250418_1910'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            #TODO Using default shop 1 could create a lot of confusion at first.
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
            preserve_default=False,
        ),
    ]
