# Generated by Django 5.2.5 on 2025-08-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
