# Generated by Django 5.1.2 on 2025-04-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
