# Generated by Django 5.1.2 on 2025-08-10 23:31

from django.db import migrations

def seed_subscription_plans(apps, _):
    SubscriptionPlan = apps.get_model('shop', 'SubscriptionPlan')

    plans = [
        {
            'name': 'Básico',
            'slug': 'basic',
            'price': 2.99,
            'description': 'Plan ideal para comenzar',
            'features': """Gestión de pedidos\nGestión de productos\n50 productos máx.\nSoporte por correo"""
        },
        {
            'name': 'Estándar',
            'slug': 'standard',
            'price': 4.99,
            'description': 'El más popular para negocios en crecimiento',
            'features': """Todo en Básico\nGestión de inventario\n200 productos máx.\nSoporte prioritario\nInformes básicos"""
        },
        {
            'name': 'Premium',
            'slug': 'premium',
            'price': 6.99,
            'description': 'Para negocios establecidos',
            'features': """Todo en Estándar\nSistema de chat\nProductos ilimitados\nSoporte 24/7\nInformes avanzados\nPromociones destacadas"""
        }
    ]

    for plan_data in plans:
        SubscriptionPlan.objects.get_or_create(
            slug=plan_data['slug'],
            defaults=plan_data
        )

def unseed_ubscription_plans(apps, _):
    SubscriptionPlan = apps.get_model('shop', 'SubscriptionPlan')
    SubscriptionPlan.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subscription_subscriptionplan_delete_customer_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_subscription_plans, reverse_code=unseed_ubscription_plans),
    ]
